export const portfolioCategories = [
  { slug: 'cbt-laboratories', icon: 'CBT', title: 'CBT Laboratory Deployments', description: 'Complete computer-based testing environments designed for dependable examination delivery.', highlights: ['Workstation deployment', 'Local network design', 'Power resilience'] },
  { slug: 'security-systems', icon: 'SEC', title: 'CCTV & Security Systems', description: 'Purpose-led surveillance and security infrastructure for clearer site visibility.', highlights: ['Camera positioning', 'Recording systems', 'Remote access planning'] },
  { slug: 'structured-cabling', icon: 'CAB', title: 'Structured Cabling', description: 'Organized copper and fiber pathways that make digital infrastructure easier to operate.', highlights: ['Cable pathways', 'Rack termination', 'Testing and labeling'] },
  { slug: 'computer-networking', icon: 'NET', title: 'Computer Networking', description: 'Secure, supportable LAN and WAN foundations for daily business operations.', highlights: ['Network architecture', 'Switching and routing', 'Segmentation'] },
  { slug: 'wireless-infrastructure', icon: 'WiFi', title: 'Wireless Infrastructure', description: 'Coverage-led wireless systems planned around people, devices, and physical spaces.', highlights: ['Coverage planning', 'Access point deployment', 'Guest connectivity'] },
  { slug: 'server-systems', icon: 'SYS', title: 'Server & Systems Deployment', description: 'Compute, storage, and operating environments prepared for dependable service delivery.', highlights: ['Server installation', 'Systems configuration', 'Documentation'] },
  { slug: 'power-backup', icon: 'UPS', title: 'Power Backup & UPS', description: 'Protected power for critical technology loads and controlled service continuity.', highlights: ['Load assessment', 'UPS deployment', 'Power protection'] },
  { slug: 'solar-energy', icon: 'SOL', title: 'Solar & Energy Solutions', description: 'Practical solar and storage systems shaped by measured operating requirements.', highlights: ['Energy assessment', 'PV and storage', 'Hybrid power'] },
  { slug: 'software-deployment', icon: 'APP', title: 'Software Deployment', description: 'Business applications configured and introduced around real operational workflows.', highlights: ['Environment setup', 'User enablement', 'Deployment support'] },
  { slug: 'cbos-deployments', icon: 'CBOS', title: 'CBOS Customer Deployments', description: 'A future-ready category for documented Carthage Business Operating System implementations.', highlights: ['Workflow discovery', 'CBOS configuration', 'Adoption support'], future: true },
];

export const projects = [
  {
    slug: 'secondary-school-cbt-deployment',
    title: 'Secondary School CBT Deployment',
    category: 'cbt-laboratories',
    industry: 'Education',
    location: null,
    summary: 'A representative case-study structure for a school computer-based testing environment, prepared for verified project details and photography.',
    overview: 'This preliminary case study documents the type of coordinated technology work involved in preparing a secondary-school CBT environment. Photographs, site context, and confirmed project particulars will be added when approved for publication.',
    challenge: 'CBT environments bring workstation readiness, local connectivity, power quality, room layout, and examination-day support into one operational system. Final site-specific constraints are intentionally not stated here until the project record is expanded.',
    solution: 'The documented delivery model combines site assessment, laboratory layout, structured connectivity, workstation preparation, network configuration, power protection, testing, and handover. Exact equipment and scope will be confirmed in a future update.',
    outcome: 'The intended business outcome is a maintainable testing environment that the school team can operate with confidence. No performance figures or customer claims are presented while the public case study remains preliminary.',
    technologies: ['CBT workstations', 'Structured LAN', 'Network switching', 'UPS protection'],
    services: ['Site assessment', 'Laboratory planning', 'Installation', 'Configuration', 'Testing and handover'],
    timeline: ['Discovery & survey', 'Infrastructure preparation', 'Systems deployment', 'Testing & handover'],
    heroImage: null,
    gallery: [],
    featured: true,
  },
  {
    slug: 'enterprise-cctv-installation',
    title: 'Enterprise CCTV Installation',
    category: 'security-systems',
    industry: 'Commercial Facilities',
    location: null,
    summary: 'A publication-ready framework for an enterprise surveillance installation, awaiting approved site imagery and final project details.',
    overview: 'This placeholder case study reflects Carthage Technologies’ engineering approach to multi-zone CCTV deployments. It will be expanded with approved photographs, equipment schedules, and customer-authorized context.',
    challenge: 'Useful surveillance depends on camera purpose, field of view, lighting, retention, network capacity, operator access, and maintainability—not camera count alone.',
    solution: 'The delivery approach covers site-risk review, coverage planning, cable routing, camera and recorder deployment, network configuration, viewing permissions, validation, and operator handover. Project-specific selections remain to be documented.',
    outcome: 'The target outcome is clearer operational visibility and a supportable evidence-retention workflow. Verified customer outcomes will be published only when available and authorized.',
    technologies: ['IP cameras', 'Network video recording', 'PoE switching', 'Secure remote viewing'],
    services: ['Security survey', 'Coverage design', 'Cabling', 'Device installation', 'Operator handover'],
    timeline: ['Site review', 'Coverage design', 'Installation', 'Commissioning'],
    heroImage: null,
    gallery: [],
    featured: true,
  },
  {
    slug: 'office-network-infrastructure',
    title: 'Office Network Infrastructure',
    category: 'computer-networking',
    industry: 'Professional Services',
    location: null,
    summary: 'A structured office networking case study ready to receive verified scope, topology, and installation photographs.',
    overview: 'This preliminary project profile demonstrates how an office network engagement can be documented from physical cabling through active network services. Verified client and location information has not been published.',
    challenge: 'Growing offices need consistent wired and wireless access, organized equipment, sensible separation of traffic, and clear records for future support.',
    solution: 'The representative scope connects structured cabling, rack organization, switching, routing, wireless coverage, labeling, testing, and as-built documentation into one deployment process.',
    outcome: 'The engineering objective is a clean, understandable network foundation that can support current operations and planned growth. Confirmed project results will be added later.',
    technologies: ['Category cabling', 'Managed switching', 'Routing', 'Business Wi-Fi'],
    services: ['Network assessment', 'Cabling and termination', 'Rack setup', 'Configuration', 'Documentation'],
    timeline: ['Requirements', 'Physical infrastructure', 'Network configuration', 'Acceptance testing'],
    heroImage: null,
    gallery: [],
    featured: true,
  },
  {
    slug: 'retail-technology-deployment',
    title: 'Retail Technology Deployment',
    category: 'software-deployment',
    industry: 'Retail',
    location: null,
    summary: 'A future-expandable record of a coordinated retail technology rollout spanning business software and site infrastructure.',
    overview: 'This case-study placeholder shows how Carthage Technologies will present combined retail software and infrastructure deployments. Customer identity, photographs, and final scope are intentionally withheld pending publication approval.',
    challenge: 'Retail technology must connect user workflows, endpoints, peripherals, connectivity, access controls, and practical staff adoption without disrupting daily trading.',
    solution: 'The representative delivery method includes workflow discovery, environment preparation, application setup, endpoint and peripheral configuration, user orientation, validation, and post-deployment support planning.',
    outcome: 'The intended outcome is a coherent operating environment that helps the retail team work consistently. Specific operational results will be included only after verification.',
    technologies: ['Business software', 'Retail endpoints', 'Local networking', 'User access controls'],
    services: ['Workflow discovery', 'Environment setup', 'Software deployment', 'User orientation', 'Support planning'],
    timeline: ['Workflow review', 'Environment setup', 'Deployment', 'Adoption support'],
    heroImage: null,
    gallery: [],
    featured: true,
  },
];

export const projectMap = Object.fromEntries(projects.map((project) => [project.slug, project]));
export const categoryMap = Object.fromEntries(portfolioCategories.map((category) => [category.slug, category]));
