export const availabilityLabels = {
  current: 'Available in current CBOS foundation',
  core: 'Core capability available',
  planned: 'Specialist workflow planned',
  future: 'Future industry edition',
};

export const industries = [
  {
    slug: 'retail',
    name: 'Retail',
    audience: 'Retailers, supermarkets, and store operators',
    status: 'current',
    title: 'Retail operations with stronger sales, stock, and customer control',
    description: 'CBOS is most mature around practical retail workflows: point-of-sale operations, inventory visibility, barcode handling, receipts, customer records, and store reporting.',
    heroCopy: 'Run point-of-sale, inventory, customer activity, reporting, and branch visibility from one connected operating foundation.',
    problems: [
      'Counter sales are separated from stock records and daily reporting.',
      'Inventory accuracy drops when barcode, receiving, and returns workflows are manual.',
      'Customer loyalty, credit, and purchase history are difficult to follow.',
      'Owners lack clear visibility across stores and cash activity.',
    ],
    helps: [
      'Connect sales, receipts, stock movement, and customer records.',
      'Support barcode and label workflows for faster product lookup.',
      'Improve visibility into returns, refunds, and daily store performance.',
      'Create a stronger operating base for single-store and multi-store growth.',
    ],
    capabilities: ['Point-of-sale operations', 'Inventory accuracy', 'Barcode and label workflows', 'Returns and refunds', 'Customer loyalty and credit', 'Receipts and reporting', 'Backup and deployment'],
    workflows: ['Daily checkout and receipt handling', 'Receiving and product updates', 'Customer credit review', 'End-of-day reporting', 'Store performance review'],
    deployment: ['Windows deployment foundation', 'Offline-capable operating model', 'Backup and restore workflows', 'Role and store access controls'],
    availabilityNote: 'Retail is the clearest current CBOS fit. Public release timing and final commercial packaging should still be confirmed during consultation.',
  },
  {
    slug: 'wholesale-distribution',
    name: 'Wholesale and Distribution',
    audience: 'Wholesalers, distributors, and supply-led operators',
    status: 'core',
    title: 'Wholesale visibility across stock, suppliers, purchasing, and credit',
    description: 'CBOS supports many distribution-adjacent needs through inventory, procurement, supplier, customer credit, transfer, and reporting foundations.',
    heroCopy: 'Coordinate bulk stock, supplier activity, customer accounts, purchase workflows, and operating reports with a shared business platform.',
    problems: [
      'Bulk inventory is hard to trust when receiving and sales records are disconnected.',
      'Purchase orders, suppliers, and procurement follow-up happen across separate tools.',
      'Customer credit and payment follow-up can become unclear at volume.',
      'Transfers and margin reporting need stronger operational visibility.',
    ],
    helps: [
      'Centralize supplier, customer, inventory, and procurement records.',
      'Improve receiving and stock movement visibility.',
      'Support customer credit review and account follow-up.',
      'Give managers clearer margin and inventory reporting surfaces.',
    ],
    capabilities: ['Bulk inventory visibility', 'Supplier management', 'Purchase workflows', 'Receiving', 'Customer credit', 'Stock transfers', 'Margin and inventory reporting'],
    workflows: ['Supplier review', 'Purchase planning', 'Goods receiving', 'Customer account review', 'Transfer monitoring'],
    deployment: ['Branch-aware setup', 'Backup and restore planning', 'Role-based access', 'REST API integration foundation'],
    availabilityNote: 'Core CBOS workflows are relevant now. Specialist distribution features such as advanced warehouse routing or complex logistics workflows are future enhancements.',
  },
  {
    slug: 'pharmacy',
    name: 'Pharmacy',
    audience: 'Pharmacies and medicine retailers',
    status: 'planned',
    title: 'Pharmacy retail foundations without unsupported clinical claims',
    description: 'CBOS can support pharmacy-adjacent retail operations such as stock visibility, barcode workflows, procurement, customer records, reporting, auditability, and access controls.',
    heroCopy: 'Use the retail and inventory foundation of CBOS for pharmacy store operations while treating compliance-specific workflows as planned specialist work.',
    problems: [
      'Stock visibility, supplier records, and procurement follow-up need better structure.',
      'Customer and branch reporting can be scattered across manual records.',
      'Access control and backup discipline are important for sensitive retail operations.',
      'Compliance-specific workflows require careful planning before claims are made.',
    ],
    helps: [
      'Support barcode-driven inventory and supplier management.',
      'Provide customer records, reporting, audit logs, and controlled access foundations.',
      'Create a base for future pharmacy-specific edition planning.',
      'Keep compliance-sensitive capabilities clearly marked as planned.',
    ],
    capabilities: ['Stock visibility', 'Barcode workflows', 'Supplier and procurement management', 'Customer records', 'Multi-branch reporting', 'Auditability', 'Backup and access controls'],
    workflows: ['Stock review', 'Supplier ordering', 'Receiving', 'Branch reporting', 'Access review'],
    deployment: ['Role-based access', 'Protected sessions', 'Configuration masking', 'Backup verification'],
    availabilityNote: 'CBOS does not currently claim prescription processing, controlled-drug compliance, clinical workflows, or regulatory integrations. Pharmacy-specific compliance workflows are planned specialist capabilities.',
  },
  {
    slug: 'hospitality',
    name: 'Hospitality',
    audience: 'Hospitality businesses with sales and inventory operations',
    status: 'future',
    title: 'Hospitality operating foundations with specialist workflows planned',
    description: 'CBOS can support transferable business workflows such as sales, customer records, inventory, procurement, branch visibility, reporting, and administration.',
    heroCopy: 'Bring sales, customer, stock, purchasing, reporting, and administration into one platform while specialist hospitality workflows remain future edition work.',
    problems: [
      'Sales, inventory, procurement, and reporting may live in separate systems.',
      'Customer records and administrative controls are difficult to standardize.',
      'Branch visibility matters when hospitality operations expand across sites.',
      'Specialist workflows need purpose-built design before launch claims are made.',
    ],
    helps: [
      'Connect transferable sales, inventory, procurement, and reporting workflows.',
      'Support customer records and administrative permissions.',
      'Provide a foundation for future hospitality-specific editions.',
      'Separate current platform capability from planned specialist features.',
    ],
    capabilities: ['Sales management', 'Customer records', 'Inventory and procurement', 'Branch visibility', 'Reporting', 'Administration'],
    workflows: ['Sales review', 'Inventory replenishment', 'Supplier follow-up', 'Customer record keeping', 'Management reporting'],
    deployment: ['Multi-location deployment planning', 'Access controls', 'Backup and restore', 'System health administration'],
    availabilityNote: 'CBOS does not currently claim room booking, property management, restaurant table management, or kitchen display systems. Those specialist workflows are future edition opportunities.',
  },
  {
    slug: 'professional-services',
    name: 'Professional Services',
    audience: 'Service businesses, offices, and growing advisory teams',
    status: 'core',
    title: 'Customer, payment, document, and reporting foundations for service teams',
    description: 'CBOS can help service-led businesses manage customers, service sales, payments, documents, reporting, access controls, and multi-branch administration.',
    heroCopy: 'Give service teams a clearer operating layer for customers, payments, receipts, documents, reporting, and administration.',
    problems: [
      'Customer records, payment notes, and service sales may be scattered.',
      'Receipts, documents, and reporting need consistent handling.',
      'Branch administration becomes difficult as teams grow.',
      'Access control is needed without adding heavy operational complexity.',
    ],
    helps: [
      'Centralize customer records and payment-related workflows.',
      'Support service sales, receipts, and documents.',
      'Improve reporting and administration for growing teams.',
      'Keep access controls aligned with roles and branches.',
    ],
    capabilities: ['Customer management', 'Payments', 'Service sales', 'Reporting', 'Multi-branch administration', 'Documents and receipts', 'Access controls'],
    workflows: ['Customer intake', 'Service sale recording', 'Payment review', 'Receipt handling', 'Management reporting'],
    deployment: ['Role permissions', 'Branch-aware administration', 'Backup planning', 'Protected sessions'],
    availabilityNote: 'CBOS does not currently claim project accounting, time tracking, or specialist billing automation. Those should be scoped separately if needed.',
  },
  {
    slug: 'multi-branch',
    name: 'Multi-branch Businesses',
    audience: 'Businesses expanding across multiple stores or operating sites',
    status: 'core',
    title: 'Store-aware architecture for businesses growing beyond one branch',
    description: 'CBOS is designed around a store-aware foundation: shared catalog control, store-specific inventory, role and store access, transfers, reporting, and centralized oversight.',
    heroCopy: 'Coordinate products, inventory, transfers, permissions, and performance reporting across multiple operating locations.',
    problems: [
      'Each branch can develop its own stock records and operating habits.',
      'Owners need visibility without manually collecting reports from every store.',
      'Transfers, roles, and store access need clear rules.',
      'Backup and deployment planning becomes more important as locations grow.',
    ],
    helps: [
      'Use one shared product catalog with store-specific inventory views.',
      'Support role and store-aware permissions.',
      'Track transfers and branch performance reporting.',
      'Provide a stronger foundation for centralized oversight and deployment planning.',
    ],
    capabilities: ['Shared product catalog', 'Store-specific inventory', 'Role and store access', 'Transfers', 'Store performance reporting', 'Centralized oversight', 'Backup and deployment foundations'],
    workflows: ['Branch setup', 'Product catalog control', 'Inventory transfer review', 'Store access management', 'Performance reporting'],
    deployment: ['Store-aware deployment planning', 'Access control review', 'Backup and restore workflows', 'System health monitoring'],
    availabilityNote: 'Multi-store readiness is a meaningful CBOS foundation. Final deployment shape depends on business size, branch process, and rollout planning.',
  },
];

export const industryMap = Object.fromEntries(industries.map((industry) => [industry.slug, industry]));
