import DocsBreadcrumbs from '../shared/DocsBreadcrumbs';
import DocsStatusBadge from '../shared/DocsStatusBadge';
import DocsCallout from '../shared/DocsCallout';
import DocsTableOfContents from '../shared/DocsTableOfContents';
import DocsNextPrevious from '../shared/DocsNextPrevious';
import DocsCTA from '../shared/DocsCTA';

export default function DocsArticleLayout({ doc, previous, next }) {
  return <main className="min-w-0"><DocsBreadcrumbs title={doc.title} /><div className="mt-8 grid gap-10 xl:grid-cols-[minmax(0,1fr)_14rem]"><article className="min-w-0"><header className="border-b border-slate-800 pb-10"><DocsStatusBadge status={doc.status} /><p className="mt-5 text-xs font-black uppercase tracking-[0.2em] text-cyan-300">{doc.category}</p><h1 className="mt-3 text-4xl font-black tracking-tight text-white sm:text-6xl">{doc.title}</h1><p className="mt-5 max-w-3xl text-base leading-8 text-slate-300">{doc.description}</p></header><div className="mt-10 space-y-12">{doc.sections.map((section) => <section key={section.id} id={section.id} className="scroll-mt-28"><h2 className="text-2xl font-black tracking-tight text-white sm:text-3xl">{section.title}</h2>{section.paragraphs?.map((paragraph) => <p key={paragraph} className="mt-4 text-base leading-8 text-slate-300">{paragraph}</p>)}{section.bullets && <ul className="mt-5 space-y-3 text-base leading-7 text-slate-300">{section.bullets.map((item) => <li key={item} className="flex gap-3"><span aria-hidden="true" className="mt-1 text-cyan-300">—</span><span>{item}</span></li>)}</ul>}{section.links && <div className="mt-5 grid gap-3 sm:grid-cols-2">{section.links.map(([label, href]) => <a key={href} href={href} className="rounded-md border border-slate-800 bg-slate-900/60 p-4 font-bold text-cyan-100 transition hover:border-cyan-300/40 focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">{label} <span aria-hidden="true">→</span></a>)}</div>}{section.callout && <DocsCallout type={section.callout.type}>{section.callout.text}</DocsCallout>}</section>)}</div><DocsCTA /><DocsNextPrevious previous={previous} next={next} /></article><div className="hidden xl:block"><div className="sticky top-24"><DocsTableOfContents sections={doc.sections} /></div></div></div></main>;
}
